Fix build with -DWITH_SIMULATION=FALSE
simulation.qrc isn't added to the build when WITH_SIMULATION is
disabled and thus building errors out with "undefined reference to
`qInitResources_simulation()'".